### ISSUE TITLE
flat material generation doesn't work

### ISSUE THREAD

**Issue by HeteroChromia42** [Pyogenics/CleanTF2plus#3]
as the title says, flat material generation doesn't work. i've tried to generate flat materials with this script, and it silently fails at flat texturizing stuff. Running Debian 11 with Wine 8.0 and Imagemagick.

**Comment by Pyogenics** [comment]
Have you tried pack_vpk.sh? I couldn't get the textures to show without packing into a vpk. Unsure why. (Sorry for late reply, I didn't get a notification)

**Comment by HeteroChromia42** [comment]
tried with pack_vpk.sh, textures is the only thing that remained unchanged despite running it with it on.

**Comment by Pyogenics** [comment]
Strange, did you select to resize the textures or not? I haven't tried the unresized option myself yet.

**Comment by Pyogenics** [comment]
Just tried it on my Arch machine and it seems to be working on my end.
![20230228191619_1](https://user-images.githubusercontent.com/82675800/221956593-51bb930a-b545-46ad-97f9-882dd066d5e5.jpg)

**Comment by Pyogenics** [comment]
I believe that you can't use unresized flat textures on casual servers (sv_pure stuff). But resized flat seems to work.

**Comment by Pyogenics** [comment]
Casual:
![20230228192455_1](https://user-images.githubusercontent.com/82675800/221958107-c8626e41-1acd-4edf-924b-b51df85e0d3a.jpg)
Local server:
![20230228192544_1](https://user-images.githubusercontent.com/82675800/221958143-7394b47b-25cc-4c35-b2f8-8fec52051fbf.jpg)

**Comment by Pyogenics** [comment]
So enable the resizing option when running the script :smiley:, if you want to play on more strict sv_pure servers. If you don't have any other questions or problems feel free to close.

**Comment by HeteroChromia42** [comment]
i apologize for a delayed response, i wasn't available until today due to an hectic week. i'm currently reinstalling both wine and imagemagick just to double-check if it wasn't a dependency issue from my end.

**Comment by Pyogenics** [comment]
Did my most recent recommendation not work?

**Comment by HeteroChromia42** [comment]
before my attempt at reinstalling wine and imagemagick, no.

**Comment by Pyogenics** [comment]
You may get a prompt from wine on first run to do with dotnet I think. Try run one of the exes in the repo manually.

**Comment by HeteroChromia42** [comment]
oh, so an app depended on mono? that might the reason it didn't work then

**Comment by Pyogenics** [comment]
Maybe, I remember the first time I ran the script wine asked to install something. Here the output is silenced so you don't get a prompt.

**Comment by HeteroChromia42** [comment]
i decided to remove the commands that silenced output, and i think i found the root of the problem.

"dev/linux/HLExtract: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by dev/linux/HLExtract)"

Debian Stable's libC is a bit older than this version that it requires, so it won't work.

**Comment by Pyogenics** [comment]
Oh damn, I can't compile a new version of HLExtract right now. Will look tomorrow.

**Comment by HeteroChromia42** [comment]
i could try it myself if i knew how to do it.

**Comment by Pyogenics** [comment]
In the meantime you could try compiling it for your own system, perhaps?

**Comment by HeteroChromia42** [comment]
yeah i was going to get to that. do you have instructions for compiling this?

**Comment by Pyogenics** [comment]
```bash
git clone https://github.com/mittorn/hllib
cd hllib
cd HLLib
make -j$(nproc)
```

**Comment by Pyogenics** [comment]
I can't remember precisely where the binaries are generated. But replace the one inside CleanTF2 dev/linux with it and any libs you find in dev/linux/lib

**Comment by HeteroChromia42** [comment]
Okay, the libs i compiled worked.

**Comment by HeteroChromia42** [comment]
i opened a repo with my versions of the libraries, feel free to test it yourself if you wish as i'm not sure if it'll work for arch.

**Comment by Pyogenics** [comment]
I will likely build a statically linked version of the binary and bypass the need for extra libs entirely.

**Comment by HeteroChromia42** [comment]
Probably the smartest move.

**Comment by Pyogenics** [comment]
Haven't been able to work on this until recently, built hllib as static successfully but not hlextract. It has problems linking against the static version of hllib that I'm not sure how to fix.

Though, hllib isn't the issue but the GNUC library is due to the version miss match we found earlier. So instead I will try a hybrid, link hlextract with static GNUC and use the exisitng hllib library. Will try it out tomorrow and, hopefully, finally close this issue with a PR upstream.

**Comment by Pyogenics** [comment]
Got static builds to work, here's my [fork](https://github.com/Pyogenics/hllib/tree/cmake) of hllib to do it. Will submit a PR upstream now.
